// Auto-generated by model/tpu_compiler.py.

    localparam int NUM_TESTS     = 1;
    localparam int MAX_CMD_COUNT = 1683;
    localparam int MAX_W_ROWS    = 17252;
    localparam int MAX_A_ROWS    = 800;
    localparam int MAX_R_ROWS    = 800;

    localparam int TEST_M          [NUM_TESTS] = '{32};
    localparam int TEST_K          [NUM_TESTS] = '{784};
    localparam int TEST_N          [NUM_TESTS] = '{10};
    localparam int TEST_CMD_COUNT  [NUM_TESTS] = '{1683};
    localparam int TEST_W_ROWS     [NUM_TESTS] = '{17252};
    localparam int TEST_A_ROWS     [NUM_TESTS] = '{800};
    localparam int TEST_R_ROWS     [NUM_TESTS] = '{800};
    localparam int TEST_RSTALL     [NUM_TESTS] = '{0};
    localparam int TEST_WSTALL     [NUM_TESTS] = '{0};
    localparam int TEST_ASTALL     [NUM_TESTS] = '{0};
    localparam string TEST_NAME [NUM_TESTS] = '{"mnist_mlp"};
