// Auto-generated by directed/gen_suite.py.

    localparam int NUM_TESTS     = 28;
    localparam int MAX_CMD_COUNT = 57;
    localparam int MAX_W_ROWS    = 192;
    localparam int MAX_A_ROWS    = 192;
    localparam int MAX_R_ROWS    = 288;

    localparam int TEST_M          [NUM_TESTS] = '{32, 32, 32, 32, 64, 64, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 96};
    localparam int TEST_K          [NUM_TESTS] = '{32, 32, 32, 64, 32, 64, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 5, 32, 32, 17, 32, 64};
    localparam int TEST_N          [NUM_TESTS] = '{32, 32, 32, 32, 32, 64, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 96};
    localparam int TEST_CMD_COUNT  [NUM_TESTS] = '{2, 5, 5, 9, 8, 28, 5, 6, 5, 1, 8, 5, 17, 12, 9, 18, 5, 5, 5, 11, 9, 2, 5, 6, 8, 5, 5, 57};
    localparam int TEST_W_ROWS     [NUM_TESTS] = '{0, 32, 32, 64, 32, 128, 32, 32, 32, 0, 0, 0, 128, 64, 64, 32, 32, 32, 32, 32, 32, 0, 32, 32, 36, 32, 32, 192};
    localparam int TEST_A_ROWS     [NUM_TESTS] = '{32, 32, 32, 64, 64, 128, 32, 32, 32, 0, 128, 96, 32, 32, 32, 128, 32, 32, 32, 32, 32, 32, 32, 32, 32, 40, 32, 192};
    localparam int TEST_R_ROWS     [NUM_TESTS] = '{32, 32, 32, 32, 64, 128, 32, 64, 32, 0, 128, 64, 128, 96, 64, 256, 32, 32, 32, 224, 96, 32, 32, 64, 64, 32, 32, 288};
    localparam int TEST_RSTALL     [NUM_TESTS] = '{0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1};
    localparam int TEST_WSTALL     [NUM_TESTS] = '{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1};
    localparam int TEST_ASTALL     [NUM_TESTS] = '{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1};
    localparam string TEST_NAME [NUM_TESTS] = '{"ub_load_read", "gemm_basic", "gemm_signed", "gemm_multi_k", "weight_reuse", "multi_tile_slot", "requant_relu", "store_read_ub", "ready_stall", "nop_command", "ub_bank_boundary", "ub_overwrite", "wmem_bank_boundary", "preload_switch_reuse", "activation_reuse", "dst_slot_isolation", "activation_code_sweep", "weight_code_sweep", "relu_mixed_sign", "requant_boundary", "acc_init_restart", "read_ub_stall", "k_valid_tail", "act_mode_none", "bias_init", "activation_mask", "input_valid_gap", "rectangular_tiles"};
