+incdir+./
-sverilog ./define.vh
-sverilog ./WPU.sv
-sverilog ./WMEM_Wrapper.sv
-sverilog ./CMEM.sv
-sverilog ./UB_Wrapper.sv
-sverilog ./Data_Setup.sv
-sverilog ./RPE.sv
-sverilog ./RSA.sv
-sverilog ./CPE.sv
-sverilog ./CSA.sv
-sverilog ./ACC.sv
-sverilog ./OP.sv
-sverilog ./TSC.sv
-sverilog ./TPU.sv
-sverilog ../00_TESTBED/PATTERN.sv
-sverilog ../00_TESTBED/TESTBED.sv
-v /usr/cad/ADFP/Executable_Package/Collaterals/IP/sram/N16ADFP_SRAM/VERILOG/N16ADFP_SRAM_100a.v
