/******************************************************************************
* Copyright (C) 2026 Marco
*
* File Name:    PATTERN.sv
* Project:      tpu-accelerator-lite
* Module:       PATTERN (TPU top table-driven suite runner)
* Author:       Marco <harry2963753@gmail.com>
* Student ID:   M11407439
* Tool:         VCS & Verdi
*
* Table-driven verification : the whole suite is described by test_suite.svh
* (auto-generated by python/gen_suite.py). This runner loops every case, loads
* its per-test .dat, drives one matmul job, and self-checks r_data vs golden.
*
* The .dat files hold only UNIQUE data ; this runner replays them in the order
* the DUT asks for, because the DUT re-fetches the same tile many times :
*   weight     stream mt->nt->kt->r  ==>  idx = i % (NT*KT*16)
*   activation stream mt->nt->kt->m  ==>  idx = mt*KT*16 + kt*16 + m
*   golden     stream mt->nt->m      ==>  idx = i
* Without this the 1024^3 weight file would be 4.2M lines / 138 MB.
*
* Overflow-corner cases (TEST_XMISS=1) are reverse-judged (a mismatch is the
* pass condition). Mismatches are $display'd (NOT $fatal) so the whole suite
* runs to completion. All stimulus is driven on negedge (gate-safe).
******************************************************************************/

`define CLK_PERIOD 10
`ifndef TIMEOUT
    `define TIMEOUT 1000000000
`endif

module PATTERN(
    output logic clk,
    output logic rst_n,
    output logic cmd_valid,
    input cmd_ready,
    output logic [`M_W-1:0] dim_m,
    output logic [`K_W-1:0] dim_k,
    output logic [`N_W-1:0] dim_n,
    output logic [`QMULT_W-1:0] quant_mult,
    output logic [`QSHIFT_W-1:0] quant_shift,
    output logic fuse_in,
    output logic fuse_out,
    output logic w_valid,
    input w_ready,
    output logic [`W_RAW_BW-1:0] w_data,
    output logic a_valid,
    input a_ready,
    output logic [`A_BW-1:0] a_data,
    output logic r_ready,
    input r_valid,
    input [`A_BW-1:0] r_data,
    input busy,
    input done
);

    //=============================================================
    // ----------------------- Test Suite -------------------------
    //=============================================================
    `include "test_suite.svh"

    reg [`W_RAW_BW-1:0] mem_w [0:MAX_W_ROWS-1];
    reg [`A_BW-1:0] mem_a [0:MAX_A_ROWS-1];
    reg [`A_BW-1:0] mem_g [0:MAX_R_ROWS-1];

    int cur_test;       // current case index (visible in waveform)
    int err_this;       // mismatch count for the current case
    int tests_pass;
    int tests_fail;
    longint cyc = 0;    // free-running cycle counter (progress reporting)
    longint cyc_mark = 0;

    //=============================================================
    // ------------------------ Clock -----------------------------
    //=============================================================
    always #(`CLK_PERIOD/2.0) clk = ~clk;
    always @(posedge clk) cyc <= cyc + 1;

    //=============================================================
    // ------------------------- Reset ----------------------------
    //=============================================================
    task automatic reset_dut();
        begin
            force clk = 0;
            rst_n = 1;
            cmd_valid = 0;
            dim_m = 0;
            dim_k = 0;
            dim_n = 0;
            quant_mult = 0;
            quant_shift = 0;
            fuse_in = 0;
            fuse_out = 0;
            w_valid = 0;
            w_data = 0;
            a_valid = 0;
            a_data = 0;
            r_ready = 0;
            #20 rst_n = 0;
            #20 rst_n = 1;
            release clk;
            @(negedge clk);
        end
    endtask

    //=============================================================
    // ---------------------------- Tasks -------------------------
    //=============================================================
    // valid/ready producer : present a beat, advance when ready sampled high.
    // `period` folds the DUT's repeated re-fetch of the same weight tile back
    // onto the unique rows held in the .dat.
    task automatic feed_w(input int nbeats, input int period);
        begin
            w_valid = 0;
            w_data = 0;
            for (int i = 0; i < nbeats; ) begin
                w_valid = 1;
                w_data = mem_w[i % period];
                if (w_ready) i++;
                @(negedge clk);
            end
            w_valid = 0;
            w_data = 0;
        end
    endtask

    // activation repeats per nt : beat i of the mt->nt->kt->m stream maps back to
    // unique row mt*KT*16 + kt*16 + m.
    task automatic feed_a(input int nbeats, input int kt_n, input int nt_n);
        int m, ktv, mtv, idx;
        begin
            a_valid = 0;
            a_data = 0;
            for (int i = 0; i < nbeats; ) begin
                m   = i % `ARRAY_S;
                ktv = (i / `ARRAY_S) % kt_n;
                mtv = i / (`ARRAY_S * kt_n * nt_n);
                idx = mtv * kt_n * `ARRAY_S + ktv * `ARRAY_S + m;
                a_valid = 1;
                a_data = mem_a[idx];
                if (a_ready) i++;
                @(negedge clk);
            end
            a_valid = 0;
            a_data = 0;
        end
    endtask

    // Load one case's unique stimulus/golden rows.  Fail immediately if a
    // missing or malformed file leaves the first word unknown; otherwise a
    // readmemh failure only becomes a misleading X-propagation failure later.
    task automatic load_case_files(input int t);
        string w_file, a_file, g_file;
        begin
            w_file = $sformatf("../00_TESTBED/pattern/t%02d_weight.dat",     t);
            a_file = $sformatf("../00_TESTBED/pattern/t%02d_activation.dat", t);
            g_file = $sformatf("../00_TESTBED/pattern/t%02d_golden.dat",     t);

            $readmemh(w_file, mem_w);
            $readmemh(a_file, mem_a);
            $readmemh(g_file, mem_g);

            if ($isunknown(mem_w[0]))
                $fatal(1, "[ERROR] t%02d failed to load weight data: %s", t, w_file);
            if ($isunknown(mem_a[0]))
                $fatal(1, "[ERROR] t%02d failed to load activation data: %s", t, a_file);
            if ($isunknown(mem_g[0]))
                $fatal(1, "[ERROR] t%02d failed to load golden data: %s", t, g_file);

            $display("  [LOAD] t%02d w0=%032h a0=%028h g0=%028h", t,
                mem_w[0], mem_a[0], mem_g[0]);
        end
    endtask

    task automatic monitor_r(input int nbeats);
        begin
            r_ready = 1;
            for (int i = 0; i < nbeats; ) begin
                if (r_valid) begin
                    if (r_data !== mem_g[i]) begin
                        if (err_this < 8) // keep the log readable on a bad run
                            $display("  [MISMATCH] t%02d beat %0d : exp=%028h got=%028h",
                                cur_test, i, mem_g[i], r_data);
                        err_this++;
                    end
                    i++;
                end
                @(negedge clk);
            end
            r_ready = 0;
        end
    endtask

    // issue one job descriptor and stream loads + collect results concurrently
    task automatic run_job(input int t);
        int MT, KT, NT;
        int w_period, w_total, a_total, r_total;
        begin
            MT = TEST_M[t] / `ARRAY_S;
            KT = TEST_K[t] / `ARRAY_S;
            NT = TEST_N[t] / `ARRAY_S;
            w_period = NT * KT * `ARRAY_S;                       // unique weight rows
            w_total  = MT * w_period;                            // beats the DUT wants
            a_total  = TEST_FIN[t] ? 0 : MT * NT * KT * `ARRAY_S; // fused job needs none
            r_total  = MT * NT * `ARRAY_S;

            dim_m = TEST_M[t];
            dim_k = TEST_K[t];
            dim_n = TEST_N[t];
            quant_mult = TEST_QMULT[t];
            quant_shift = TEST_QSHIFT[t];
            fuse_in = TEST_FIN[t];
            fuse_out = TEST_FOUT[t];

            cmd_valid = 1;
            while (!cmd_ready) @(negedge clk);
            @(negedge clk);           // descriptor accepted -> LOADING
            cmd_valid = 0;

            fork
                feed_w(w_total, w_period);
                feed_a(a_total, KT, NT);
                monitor_r(r_total);
            join

            fuse_in = 0;
            fuse_out = 0;
        end
    endtask

    // pass/fail decision : normal cases need 0 mismatch ; overflow corners
    // (TEST_XMISS=1) are reverse-judged (a mismatch is expected).
    task automatic judge(input int t);
        logic ok;
        string tag;
        begin
            if (TEST_XMISS[t]) ok = (err_this > 0);
            else ok = (err_this == 0);
            if (TEST_XMISS[t]) tag = "(expected mismatch)";
            else tag = "";
            if (ok) begin
                tests_pass++;
                $display("  [PASS] t%02d %-18s err=%0d  cyc=%0d %s",
                    t, TEST_NAME[t], err_this, cyc - cyc_mark, tag);
            end
            else begin
                tests_fail++;
                $display("  [FAIL] t%02d %-18s err=%0d  cyc=%0d %s",
                    t, TEST_NAME[t], err_this, cyc - cyc_mark, tag);
            end
        end
    endtask

    task automatic end_task();
        begin
            $display("============================================");
            if (tests_fail == 0)
                $display("  [SUCCESS] ALL %0d / %0d TESTS PASS !", tests_pass, NUM_TESTS);
            else
                $display("  [FAILURE] %0d / %0d TESTS FAILED", tests_fail, NUM_TESTS);
            $display("  total cycles : %0d", cyc);
            $display("============================================");
        end
    endtask

    //=============================================================
    // ------------------------- Timing Watchdog ------------------
    //=============================================================
    initial begin
        #(`TIMEOUT);
        $display("  [ERROR] watchdog fired in t%02d after %0d cycles", cur_test, cyc);
        $fatal(1, "[ERROR] : Simulation time exceeded watchdog limit.");
    end

    //=============================================================
    // ------------------------ Protocol SVA ----------------------
    //=============================================================
    `ifdef SVA
        // IDLE (cmd_ready) and busy are mutually exclusive
        CHECK_IDLE_BUSY: assert property (@(posedge clk) disable iff(!rst_n)
            !(cmd_ready && busy));
        // a stalled result beat must hold valid + data stable until accepted
        CHECK_R_STABLE: assert property (@(posedge clk) disable iff(!rst_n)
            (r_valid && !r_ready) |=> (r_valid && $stable(r_data)));
        // ---- descriptor legality : the RTL derives tile counts with a shift and
        // ---- never validates, so an illegal job is silently mis-computed.
        CHECK_DIM_ALIGN: assert property (@(posedge clk) disable iff(!rst_n)
            (cmd_valid && cmd_ready) |->
            (dim_m[`ROW_IDX_W-1:0] == 0 && dim_k[`ROW_IDX_W-1:0] == 0
                                        && dim_n[`ROW_IDX_W-1:0] == 0));
        CHECK_DIM_RANGE: assert property (@(posedge clk) disable iff(!rst_n)
            (cmd_valid && cmd_ready) |->
            (dim_m != 0 && dim_k != 0 && dim_n != 0 &&
             dim_m <= `M_MAX && dim_k <= `K_MAX && dim_n <= `N_MAX));
        // ---- fusion legality : OBUF holds 8 x 16 rows and its write address
        // ---- ignores mt, so anything wider aliases.
        CHECK_FUSE_OUT: assert property (@(posedge clk) disable iff(!rst_n)
            (cmd_valid && cmd_ready && fuse_out) |->
            (dim_m <= `ARRAY_S && dim_n <= `OBUF_D));
        CHECK_FUSE_IN: assert property (@(posedge clk) disable iff(!rst_n)
            (cmd_valid && cmd_ready && fuse_in) |->
            (dim_m <= `ARRAY_S && dim_k <= `OBUF_D));
    `endif

    //=============================================================
    // ------------------------- Main Flow ------------------------
    //=============================================================
    initial begin
        tests_pass = 0;
        tests_fail = 0;
        err_this = 0;
        cur_test = 0;

        for (int t = 0; t < NUM_TESTS; t++) begin
            cur_test = t;
            if (TEST_NEWSEQ[t]) reset_dut();
            load_case_files(t);
            err_this = 0;
            cyc_mark = cyc;
            $display("  [RUN ] t%02d %-18s M=%0d K=%0d N=%0d", t, TEST_NAME[t],
                TEST_M[t], TEST_K[t], TEST_N[t]);
            run_job(t);
            judge(t);
        end

        end_task();
        $finish;
    end

endmodule
