// AUTO-GENERATED by gen_suite.py -- do not edit by hand.
// Regenerate : python3 python/gen_suite.py [--big]

    localparam int NUM_TESTS  = 32;
    // .dat file lengths (unique data ; PATTERN replays them)
    localparam int MAX_W_ROWS = 16384;
    localparam int MAX_A_ROWS = 16384;
    localparam int MAX_R_ROWS = 16384;
    localparam int TEST_M [NUM_TESTS] = '{16, 32, 128, 16, 128, 64, 16, 32, 16, 1024, 16, 512, 16, 64, 32, 16, 16, 16, 16, 16, 32, 16, 48, 16, 16, 512, 16, 96, 96, 16, 128, 64};
    localparam int TEST_K [NUM_TESTS] = '{16, 32, 128, 128, 16, 48, 512, 1024, 4096, 16, 16, 16, 16, 64, 512, 16, 16, 16, 16, 4096, 32, 64, 16, 16, 32, 512, 64, 256, 128, 64, 128, 64};
    localparam int TEST_N [NUM_TESTS] = '{16, 32, 128, 16, 128, 32, 16, 32, 16, 16, 1024, 512, 16, 64, 32, 16, 16, 16, 16, 16, 32, 48, 16, 32, 16, 512, 96, 96, 32, 16, 128, 48};
    localparam int TEST_QMULT [NUM_TESTS] = '{1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 13, 1000, 5, 131071, 1, 1, 1, 1, 1, 1, 29, 63, 11, 2, 27, 49};
    localparam int TEST_QSHIFT [NUM_TESTS] = '{0, 0, 0, 0, 0, 0, 9, 9, 10, 0, 0, 0, 0, 0, 9, 0, 7, 0, 4, 32, 0, 0, 0, 7, 7, 9, 12, 14, 11, 8, 13, 13};
    localparam int TEST_NEWSEQ [NUM_TESTS] = '{1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1};
    localparam int TEST_XMISS [NUM_TESTS] = '{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    localparam int TEST_FIN [NUM_TESTS] = '{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0};
    localparam int TEST_FOUT [NUM_TESTS] = '{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0};
    localparam string TEST_NAME [NUM_TESTS] = '{"basic_16", "basic_32", "basic_128", "basic_16x128x16", "basic_128x16x128", "basic_64x48x32", "bigk_512", "bigk_1024", "bigk_4096", "bigm_1024", "bign_1024", "bigmn_512", "comp_16", "comp_64", "comp_bigk", "comp_ovf_16", "rq_scale_16", "rq_sat_16", "rq_relu_16", "rq_shift32", "consec_a", "consec_b", "consec_c", "fuse_src", "fuse_dst", "big_512", "rand_0", "rand_1", "rand_2", "rand_3", "rand_4", "rand_5"};
