// Auto-generated by python/gen_suite.py.

    localparam int NUM_TESTS     = 9;
    localparam int MAX_CMD_COUNT = 28;
    localparam int MAX_W_ROWS    = 128;
    localparam int MAX_A_ROWS    = 128;
    localparam int MAX_R_ROWS    = 128;

    localparam int TEST_M          [NUM_TESTS] = '{32, 32, 32, 32, 64, 64, 32, 32, 32};
    localparam int TEST_K          [NUM_TESTS] = '{32, 32, 32, 64, 32, 64, 32, 32, 32};
    localparam int TEST_N          [NUM_TESTS] = '{32, 32, 32, 32, 32, 64, 32, 32, 32};
    localparam int TEST_CMD_COUNT  [NUM_TESTS] = '{2, 5, 5, 9, 8, 28, 5, 6, 5};
    localparam int TEST_W_ROWS     [NUM_TESTS] = '{0, 32, 32, 64, 32, 128, 32, 32, 32};
    localparam int TEST_A_ROWS     [NUM_TESTS] = '{32, 32, 32, 64, 64, 128, 32, 32, 32};
    localparam int TEST_R_ROWS     [NUM_TESTS] = '{32, 32, 32, 32, 64, 128, 32, 64, 32};
    localparam int TEST_RSTALL     [NUM_TESTS] = '{0, 0, 0, 0, 0, 0, 0, 0, 1};
    localparam string TEST_NAME [NUM_TESTS] = '{"ub_load_read", "gemm_basic", "gemm_signed", "gemm_multi_k", "weight_reuse", "multi_tile_slot", "requant_relu", "store_read_ub", "ready_stall"};
